#!/bin/bash

BASE_URL="http://bazel-tf-cache.nvidia.com"
SERVICE_PORT=9091

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
TF_API="$(grep "^TF_API=" ${THIS_DIR}/nvbuild.sh | cut -d= -f2)"
OS_ID="$(cat /etc/os-release | grep "^ID=" | cut -d= -f2 | cut -d'"' -f2)"
OS_VER="$(cat /etc/os-release | grep "VERSION_ID" | cut -d'"' -f2)"
ARCH="$(uname -m)"

if [[ -z ${TF_API} || -z ${OS_ID} || -z ${OS_VER} || -z ${ARCH} || -z ${BASE_CUDA_IMAGE_ID} ]]; then
    echo ""
    echo "1: $TF_API" 1>&2;
    echo "2: $OS_ID" 1>&2;
    echo "3: $OS_VER" 1>&2;
    echo "4: $ARCH" 1>&2;
    echo "5: $BASE_CUDA_IMAGE_ID" 1>&2;
    exit 0
fi

CACHE_KEY="tf${TF_API}-${OS_ID}${OS_VER}-${ARCH}-base${BASE_CUDA_IMAGE_ID}"

CACHE_URL="${BASE_URL}:${SERVICE_PORT}/${CACHE_KEY}"

TEST_ADDR="${CACHE_URL}/ac/0000000000000000000000000000000000000000000000000000000000000000"

RESPONSE="$(curl --silent --max-time 10 --connect-timeout 10 ${TEST_ADDR})"
if [[ "Not found" != "${RESPONSE}" ]]; then
  echo ""
  exit 0
fi

echo "--experimental_guard_against_concurrent_changes --remote_cache=$CACHE_URL"
