variables:
    GIT_STRATEGY: checkout
    GIT_SUBMODULE_STRATEGY: none
    BUILD_REPO: ssh://git@gitlab-master.nvidia.com:12051/dl/dgx/tensorflow

stages:
    - build

build:
  stage: build
  script:
    - export EXACT_MATCH_BUILDER=$(git ls-remote --heads --refs ${BUILD_REPO}
                                    "refs/heads/${CI_COMMIT_REF_NAME}" | wc -l)
    - if [[ "${CI_COMMIT_REF_NAME}" == "upstream" ]]; then
        export REF="upstream-build";
      elif [[ "${CI_COMMIT_REF_NAME}" == "master" ]]; then
        export REF="master-build";
      elif [[ "${EXACT_MATCH_BUILDER}" -ne 0 ]]; then
        export REF="${CI_COMMIT_REF_NAME}";
      else
        NOT_IN_MASTER="$(git rev-list --count ^origin/master ${CI_COMMIT_REF_NAME})";
        NOT_IN_UPSTREAM="$(git rev-list --count ^origin/upstream ${CI_COMMIT_REF_NAME})";
        if [[ "$NOT_IN_MASTER" -lt "$NOT_IN_UPSTREAM" ]]; then
          export REF="master-build";
        elif [[ "$NOT_IN_UPSTREAM" -lt "$NOT_IN_MASTER" ]]; then
          export REF="upstream-build";
        else
          EXTRA_IN_MASTER="$(git rev-list --count origin/master ^${CI_COMMIT_REF_NAME})";
          EXTRA_IN_UPSTREAM="$(git rev-list --count origin/upstream ^${CI_COMMIT_REF_NAME})";
          if [[ "$EXTRA_IN_MASTER" -le "$EXTRA_IN_UPSTREAM" ]]; then
            export REF="master-build";
          else
            export REF="upstream-build";
          fi;
        fi;
      fi
    - echo "Selected builder branch $REF"
    - curl -X POST 
           -F token="${CI_JOB_TOKEN}"
           -F ref="$REF" 
           -F "variables[TF_HASH]=${CI_COMMIT_SHA}"
           https://gitlab-master.nvidia.com/api/v4/projects/9743/trigger/pipeline
